### ISSUE TITLE
RegisterTwoVolumes: Register multiple 3D volumes

### ISSUE THREAD

**Issue by SmashTV** [wanderine/BROCCOLI#16]
Hi Anders,

I would like to use RegisterTwoVolumes to coregister a whole 4D time series of functionals with an anatomical scan. However, the resulting images "...aligned_linear.nii.gz" and "...aligned_nonlinear.nii.gz" are just 3D.

Is there an easy way to do that in BROCCOLI? Or is it possible to output the linear/non-linear transformations from one call to RegisterTwoVolumes and then apply them to another 4D series?

Cheers,
Michael

**Comment by wanderine** [comment]
Hi,

sorry for the late response.

No there is no easy way right now, but I can add such an option.

- Anders

2015-03-02 14:11 GMT-05:00 SmashTV <notifications@github.com>:

> Hi Anders,
>
> I would like to use RegisterTwoVolumes to coregister a whole 4D time
> series of functionals with an anatomical scan. However, the resulting
> images "...aligned_linear.nii.gz" and "...aligned_nonlinear.nii.gz" are
> just 3D.
>
> Is there an easy way to do that in BROCCOLI? Or is it possible to output
> the linear/non-linear transformations from one call to RegisterTwoVolumes
> and then apply them to another 4D series?
>
> Cheers,
> Michael
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wanderine/BROCCOLI/issues/16>.
>



-- 
Anders Eklund, PhD

**Comment by wanderine** [comment]
This has finally been added.
