### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ImmanuelSamuel** [wanderine/BROCCOLI#20]
```
Authored by K.A. Eklund 
fMRI data size: 64 x 64 x 13586 x 1 
fMRI voxel size: 3.500000 x 3.500000 x 3.500000 mm 
fMRI TR: 1.980000 s 
fMRI slice order: Seqential increasing 
T1 data size: 155 x 208 x 190 
T1 voxel size: 1.000000 x 1.000000 x 1.000000 mm 
MNI data size: 182 x 218 x 182 
MNI voxel size: 1.000000 x 1.000000 x 1.000000 mm 
Number of original GLM regressors: 1 
Number of total GLM regressors: 5 
Number of contrasts: 1 

Performing registration between T1 and MNI
Performing registration between fMRI and T1
Segmentation fault (core dumped)
```

**Comment by wanderine** [comment]
There is something strange with your fMRI data, it has 13586 slices but
only one time point?

What do you get if you run fslinfo (FSL) or 3dinfo (AFNI) for the fMRI
dataset?

2015-08-16 18:58 GMT+02:00 ImmanuelSamuel <notifications@github.com>:

> Authored by K.A. Eklund
> fMRI data size: 64 x 64 x 13586 x 1
> fMRI voxel size: 3.500000 x 3.500000 x 3.500000 mm
> fMRI TR: 1.980000 s
> fMRI slice order: Seqential increasing
> T1 data size: 155 x 208 x 190
> T1 voxel size: 1.000000 x 1.000000 x 1.000000 mm
> MNI data size: 182 x 218 x 182
> MNI voxel size: 1.000000 x 1.000000 x 1.000000 mm
> Number of original GLM regressors: 1
> Number of total GLM regressors: 5
> Number of contrasts: 1
>
> Performing registration between T1 and MNI
> Performing registration between fMRI and T1
> Segmentation fault (core dumped)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wanderine/BROCCOLI/issues/20>.
>



-- 
Anders Eklund, PhD

**Comment by ImmanuelSamuel** [comment]
I used dcm2nii converter from mricron

**Comment by wanderine** [comment]
OK I haven't used it but for some reason it puts all the fMRI data into a
single volume, instead of several volumes. I think your dataset should be
something like

64 x 64 x 34 x 400

Is there any option that you can change?

2015-08-16 19:02 GMT+02:00 ImmanuelSamuel <notifications@github.com>:

> I used dcm2nii converter from mricron
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wanderine/BROCCOLI/issues/20#issuecomment-131583561>.
>



-- 
Anders Eklund, PhD

**Comment by ImmanuelSamuel** [comment]
I am reconverting them after some changes and checking if they become like that. It is taking time for conversion will update after it is done.

**Comment by ImmanuelSamuel** [comment]
So I tried to use fslhd to look at the header to see if there is number of slices per volume tag. But I am getting this error saying couldn't open file. My linux inexperience is really showing now.

Using sudo gets me the permission but now I can read the libraries associated with fsl just like what happened yesterday.

Tried 
``` chown -R immanuel:immanuel /path to directory ```
but didnt work.

**Comment by wanderine** [comment]
Try

chmod +x filename

2015-08-16 21:12 GMT+02:00 ImmanuelSamuel <notifications@github.com>:

> So I tried to use fslhd to look at the header to see if there is number of
> slices per volume tag. But I am getting this error saying couldn't open
> file. My linux inexperience is really showing now.
>
> Using sudo gets me the permission but now I can read the libraries
> associated with fsl just like what happened yesterday.
>
> Tried
> chown -R immanuel:immanuel /path to directory
> but didnt work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wanderine/BROCCOLI/issues/20#issuecomment-131605324>.
>



-- 
Anders Eklund, PhD

**Comment by ImmanuelSamuel** [comment]
yeah it worked 3dinfo also shows 64 x 64 x 13586 ... I used other converters and they said cannot find slice per volume info in the header. So wierd.

**Comment by wanderine** [comment]
Did you try to3d in afni?

to3d -epan -prefix mynifti.nii -time:zt  nz nt TR  *.dcm

nz is the number of slices
nt is the number of time points
TR is the repetition time, in milliseconds, i.e. 2000 for 2 seconds

2015-08-16 21:27 GMT+02:00 ImmanuelSamuel <notifications@github.com>:

> yeah it worked 3dinfo also shows 64 x 64 x 13586 ... I used other
> converters and they said cannot find slice per volume info in the header.
> So wierd.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wanderine/BROCCOLI/issues/20#issuecomment-131611577>.
>



-- 
Anders Eklund, PhD

**Comment by wanderine** [comment]
Sorry should be

to3d -epan -prefix mynifti.nii -time:zt  nz nt TR timepattern *.dcm


tpattern = Code word that identifies how the slices (z-direction)

               were gathered in time.  The values that can be used:


       alt+z = altplus    = alternating in the plus direction

       alt+z2             = alternating, starting at slice #1

       alt-z = altminus   = alternating in the minus direction

       alt-z2             = alternating, starting at slice #nz-2

       seq+z = seqplus    = sequential in the plus direction

       seq-z = seqminus   = sequential in the minus direction

       zero  = simult     = simultaneous acquisition

       FROM_IMAGE         = (try to) read offsets from input images

       @filename          = read temporal offsets from 'filename'




2015-08-16 21:38 GMT+02:00 Anders Eklund <andek034@gmail.com>:

> Did you try to3d in afni?
>
> to3d -epan -prefix mynifti.nii -time:zt  nz nt TR  *.dcm
>
> nz is the number of slices
> nt is the number of time points
> TR is the repetition time, in milliseconds, i.e. 2000 for 2 seconds
>
> 2015-08-16 21:27 GMT+02:00 ImmanuelSamuel <notifications@github.com>:
>
>> yeah it worked 3dinfo also shows 64 x 64 x 13586 ... I used other
>> converters and they said cannot find slice per volume info in the header.
>> So wierd.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/wanderine/BROCCOLI/issues/20#issuecomment-131611577>.
>>
>
>
>
> --
> Anders Eklund, PhD
>
>
>


-- 
Anders Eklund, PhD

**Comment by ImmanuelSamuel** [comment]
Ok found the problem. I usually use SPM so I just reject the last two images that are usually incomplete images. This occurs due to partial acquisition. I just might have to try other converters that gives better control of conversion parameters.
